raysan5/raylib.com

index.html

As part of the workshop made April 29, 2019 we're making a first contribution.

Add contribution link on Footer

---

common/main.css

- Bottom border is now a part of the menu div, instead of each item
- Hovering no longer causes items to jump around
- Added nice hover animation using CSS transitions

Cleaned up menu navigation

---

cheatsheet/cheatsheet.html

* Fixes issue with structs/colors using css grid
* Indentation fixes

Fix cheatsheet markup

---

cheatsheet/raylib_textures.c

This updates the textures cheatsheet.

[textures] Update raylib_textures cheatsheet

---

cheatsheet/cheatsheet.html

Messed around with a lot of stuff, the CSS should work better now (all info accessible no matter the screen size), and you can also switch between light and dark theme by clicking on the corresponding boxes on the top right corner. It's pretty modular so you can add other color themes if you want as well.

Cheatsheet: Dark theme and CSS is now better

---

README.md

So... I was looking at raylib.com, then I saw this: "raylib is highly inspired by Borland BGI graphics lib and by XNA framework." I think highly isn't the right word to use. I think heavily should be used instead of highly. Please contact me on my main profile, @dugo3number2, because I am at school right now and have to use this account.

Found something that I think should be changed

---

cheatsheet/cheatsheet.html
examples.html
examples/web/audio/loader.html
examples/web/core/loader.html
examples/web/models/loader.html
examples/web/physics/loader.html
examples/web/shaders/loader.html
examples/web/shapes/loader.html
examples/web/text/loader.html
examples/web/textures/loader.html
games.html
games/loader.html

This fixes #18. All jquery.com url are replaced by Google CDN.

Fix jQuery JS file not loading

---

cheatsheet/raylib_textures.c

I added ranges for the HSV values in the cheatsheet since they are missing, but important to know imo.

Cheatsheet hsv add

---

cheatsheet/raylib_models.c
examples/web/models/models_loading.c
examples/web/models/models_mesh_picking.c

I've change all occurences of MeshBoundingBox to GetMeshBoundingBox.

Rename MeshBoundingBox to GetMeshBoundingBox

---

cheatsheet/raylib_textures.c

changed: "this functions" to "these functions"

fixed grammar mistake

---

cheatsheet/raylib_audio.c

Updated InitAudioStream to LoadAudioStream

---

cheatsheet/cheatsheet.html

link to access raylib header file in raylib's cheatsheet wiki page

added link to raylib.h file

---

cheatsheet/raylib_audio.c

Fixing mistake I made

---

index.html

Nothing big, just some things I noticed.

Fixed a couple small spelling / grammar issues in index.html

---

cheatsheet/cheatsheet.html
cheatsheet/cheatsheet_zh.html
common/common.js
common/examples.css
common/img/anchor_link.svg
common/main.css
examples.html
games.html
index.html
license.html

Stylistic changes:
- New header layout and style
- Raylib architecture diagram now has a border, and is centred.
- Features list now uses `<ul>` and `<li>` elements.
- Examples filter buttons now have a fading border animation.
Functionality changes:
- Section headers now have a right-clickable link icon for sharing.
- Architecture diagram now opens image in a new tab.
Code rework:
- Improved usage of IDs vs classes. Less repeated code.
- Usage of a variable for main width of contents.
A new Google Analytics acknowledgement banner has been added to inform visitors of the Google Analytics tracking.
**Homepage preview:**

Restyle, added functionality, code rework, +1 more change.

---

cheatsheet/cheatsheet_zh.html
cheatsheet/zh/raylib_audio.c
cheatsheet/zh/raylib_core.c
cheatsheet/zh/raylib_models.c
cheatsheet/zh/raylib_shapes.c
cheatsheet/zh/raylib_textures.c

Recently, someone has reported some errors to me, and I have made some modifications to the Chinese translation. Thank you. Can you please 
pass it? Thank you!
Thank you for your support of Raylib Chinese community！

Hello！I do some modifications

---

index.html

Updated the amount of bindings to match the github readme.

Updated website to match github readme

---

examples.html
games.html
index.html
license.html

I'm blind so idk how nice this looks. Can you guys check?

added sponsor button to navigation

---

common/main.css
examples.html
games.html
index.html
ui_manager.js

-A brand new go to top button that auto hides whenever the top is reached. It works for both mobile and desktop.
-A new file called ui_manager.js. This file will be responsible for all future ui changes, including, but not limited to:
the new mobile navigation menu, and the new navigation menu for the cheatsheet page.

Go to Top Button Update for raylib Site

---

common/main.css

I forced the pointer cursor to selectable navigation buttons in the nav bar and set the cursor to default on active nav item.

Updated navigation bar cursors.

---

common/main.css
examples.html
games.html
index.html
ui_manager.js

Updated top nav thing
